### ISSUE TITLE
Bugs: Error when build scss

### ISSUE THREAD

**Issue by hbinduni** [creativetimofficial/ct-now-ui-kit-pro-angular#2]
Hi, I try to compile scss from html v1.2.0, but got this error:
in `styles.scss`:

`@import "~bootstrap/scss/bootstrap.scss";`

in `angular.json`:
```
"styles": [
              "src/styles.scss",
              "src/assets/sass/now-ui-kit.scss",
              "src/assets/sass/demo.scss"
            ],
```

error return when `ng serve`:

```
./src/assets/sass/now-ui-kit.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/sass/now-ui-kit.scss)
Module build failed: 
@import "now-ui-kit/responsive";
                               ^
      Invalid CSS after '...it/responsive";': expected 1 selector or at-rule, was '";'
      in /Users/test-angular6/src/assets/sass/now-ui-kit.scss (line 63, column 33)
```

Can you check?
Thanks

**Comment by chelaruc** [comment]
@hbinduni can you move `@import "~bootstrap/scss/bootstrap.scss";` to the beggining of `now-ui-kit.scss` file and tell me if its working?

**Comment by hbinduni** [comment]
@chelaruc i try to move the reference but still got the same error:

```
ERROR in ./src/assets/sass/now-ui-kit.scss
Module build failed: ModuleBuildError: Module build failed: 
@import "now-ui-kit/responsive";
                               ^
      Invalid CSS after '...it/responsive";': expected 1 selector or at-rule, was '";'
      in /Users/xxx/src/assets/sass/now-ui-kit.scss (line 63, column 33)

```

**Comment by chelaruc** [comment]
@hbinduni have you updated the product to Angular 6?

**Comment by hbinduni** [comment]
I am not update the product it self. I use the html version of the product and try to make the scss working for my project which use angular 6. event without angular, the scss should be compile right?

**Comment by hbinduni** [comment]
for your reference, i just copy assets file from this folder.
<img width="580" alt="screenshot 2018-06-05 21 35 06" src="https://user-images.githubusercontent.com/1378410/40982823-6fb9c36c-6908-11e8-8a70-5e84ff1c44c0.png">

**Comment by chelaruc** [comment]
@hbinduni at line 64 you have `";`, all you have to do is to delete the line.

**Comment by hbinduni** [comment]
Hi @chelaruc , after delete the line you told before. Now i got this error:

```
ERROR in ./src/assets/sass/demo.scss
Module build failed: ModuleBuildError: Module build failed: 
}
^
      Invalid CSS after "}": expected 1 selector or at-rule, was "it-animation-name: "
      in /Users/xxxx/src/assets/sass/demo.scss (line 1559, column 2)

```

**Comment by chelaruc** [comment]
@hbinduni delete the lines 1560-1562 from demo.scss and should work

**Comment by hbinduni** [comment]
Thank you. It work
