### ISSUE TITLE
file upload not working on mobile

### ISSUE THREAD

**Issue by chelaruc** [creativetimofficial/ct-now-ui-kit-pro-angular#3]
To fix this, you need the following changes:
1) in `src/app/shared/image-upload/image-upload.component.ts`:
- change handleClick function with:
```
handleClick(){
     this.input.nativeElement.children[2].click();
}
```
- change the import at the beggining with: 
```
import { Component, OnInit, Input, ViewChild, ElementRef } from '@angular/core';
```
- add before constructor:
```
    @ViewChild('input') input: ElementRef;
```
- add the following function:
```
ngAfterViewInit(){
        this.input.nativeElement.children[2].onchange = this.handleImageChange;;
    }
```
 
2) in `src/app/shared/image-upload/image-upload.component.html`:
- change first line with:
```
<div class="fileinput text-center" #input>
```
- and inside the above `div` add:
```
<input type="file"/>
```

3) in `src/app/shared/image-upload/image-upload.component.scss` add:
```
.fileinput input{
  display: none;
}
```

All the best,
Ciprian

**Comment by merchan13** [comment]
Hi! I'm the one who ask you about this issue in <creative-tim.com>.

I followed your instructions but still doesn't work, not even in web. Am I missing something?

Thank you!

**Comment by merchan13** [comment]
Hey! I just notice that it should be 

`this.input.nativeElement.children[0]...`

Making this little fix it works like a charm, thank you so much!
