### ISSUE TITLE
Sidebar does not work

### ISSUE THREAD

**Issue by juangcarmona** [creativetimofficial/ct-now-ui-kit-pro-angular#5]
As the title says the sidebar is not being displayed. Any ideas on where to find and solve the issue?

Once downloaded and unziped the Angular Bundle I tried to build it and it didn't work, the only way to make it build (and serve it as usual with ng serve) was by updating it with ng update. but then everything worked but the sidebar (as far as I've seen)

Thanks in advance, 

Juan

PS: screenshot taken without changing a single line of code apart form the update:

1.- home page:
![image](https://user-images.githubusercontent.com/2834629/48717975-be407400-ec1a-11e8-82f9-b9cb59ce9e5f.png)

2,.- Login example page:
![image](https://user-images.githubusercontent.com/2834629/48717624-19259b80-ec1a-11e8-9474-0b2e64239789.png)

NOTE: Please, some help here, I bought this for my company (I'm creating a startup) and until now it didn't worth the effort... :(

**Comment by juangcarmona** [comment]
Well, few minutes later I was able to see the sidebar by adding [ngbCollapse]="!sidebarVisible"  (and making that filed public in the class)

**Comment by chelaruc** [comment]
@JuanGarciaCarmona Thank you for using our product. All you have to do to fix this error is to go in `src/assets/sass/now-ui-kit/mixins/_navbar.scss` file on line 4 and add `!important` to `display: block;`. 

Best, Ciprian
